run_name: CFM3_largeDS

data_params:
  data_folder: /remote/gpu03/schiller/JetCalibration/data_v2 #/Ak10Jet_1.npy
  #n_data: 1000000
  n_files_train: 50
  n_files_test: 1
  target_dims: [0,1]
  skip_dims: [8]

  target_preprocessor:
    standardize: True
  
  input_preprocessor:
    log_dims: [0, 1, 5, 6, 8, 11, 19, 20]
    standardize: True

  loader_params:
    batch_size: 65536 # 32768
    num_workers: 30
    pin_memory: true
    shuffle: true
    persistent_workers: true
    prefetch_factor: 1


model_params:
  model: MLP_CFM
  hidden_dim: 512
  num_layers: 6
  learning_rate: 0.001
  lr_sheduler_factor: 0.8
  lr_sheduler_patience: 10
  lr_threshold: 0.0
  use_silu: True

epochs: 300
save_predictions: True
n_samples: 50
compile: False

defaults:
  - classifier: classifier