run_name: CFM4_weight_decay

data_params:
  data_folder: /remote/gpu03/schiller/JetCalibration/data_v2
  n_files_train: 10
  n_files_test: 2
  target_dims: [0,1]
  skip_dims: [8]

  target_preprocessor:
    standardize: True
  
  input_preprocessor:
    log_dims: [0, 1, 5, 6, 8, 11, 19, 20]
    standardize: True

  loader_params:
    batch_size: 32768
    num_workers: 4
    pin_memory: true
    shuffle: true
    persistent_workers: true
    prefetch_factor: 4


model_params:
  model: MLP_CFM
  res_net: True
  hidden_dim: 512
  interm_dim: 1024
  num_layers: 6
  learning_rate: 0.0005
  lr_sheduler_factor: 0.9
  lr_sheduler_patience: 5
  weight_decay: 0.001

epochs: 400
save_predictions: True
n_samples: 50
use_tf32: False
