run_name: TestLarge

data_params:
  data_folder: /remote/gpu07/huetsch/JetCalibration/data_v2 #/Ak10Jet_1.npy
  #n_data: 1000000
  n_files_train: 20
  n_files_test: 4
  target_dims: [0,1]

  target_preprocessor:
    standardize: True
  
  input_preprocessor:
    log_dims: [0, 1, 5, 6, 8, 11, 19, 20]
    standardize: True

  loader_params:
    batch_size: 40960
    num_workers: 8
    pin_memory: true
    shuffle: true
    persistent_workers: true
    prefetch_factor: 4

model_params:
  model: MLP_Multivariate_GMM_Regression
  n_Gaussians: 5
  hidden_dim: 1024
  num_layers: 8
  drop: 0.2
  learning_rate: 0.0001

epochs: 200
save_predictions: False
n_samples: 50
