data_params:
  split_frac: [0.5, 0.1, 0.4]

  loader_params:
    batch_size: 65536 # 32768 # 4096
    test_batch_size: 1048576
    num_workers: 16
    pin_memory: true
    shuffle: true
    persistent_workers: true
    prefetch_factor: 1

model_params:
  model: MLP_Classifier
  use_silu: True
  hidden_dim: 256
  num_layers: 3
  drop: 0.3
  learning_rate: 0.0001
  weight_decay: 0.001
  lr_warmup_epochs: 5
  lr_sheduler_factor: 0.5
  lr_sheduler_patience: 10
  lr_threshold: 0.0
  init_scale: 0.5
  
epochs: 200